logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.apache.coyote.http11: debug #Http 요청정보 로그 남기기

#server:
  #port: 8083

# database 연동 설정
spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/gsccloset?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #username: root
    #password: 12341234
  # spring data jpa 설정
  jpa:
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    #open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true

    hibernate:
      ddl-auto: create
oauth:
  kakao:
    client_id: 3fcfbbd0e2ff98f1dba3e5567758dad0
    redirect_uri: http://localhost:3000/oauth/redirected/kakao
    client_secret: RmxyOJX4emsK3yQ2ZU46Zdxvvj48CBCC
    scope: profile_nickname, profile_image
  naver:
    client_id: nzoK10X6IukygRJeLJF2
    redirect_uri: http://localhost:3000/oauth/redirected/naver
    client_secret: kDFbiNgKoc
    scope: nickname, profileImage
  google:
    client_id: ${GOOGLE_CLIENT_ID}
    redirect_uri: ${GOOGLE_REDIRECT_URI}
    client_secret: ${GOOGLE_CLIENT_SECRET}
    scope: ${GOOGLE_SCOPE}